### ISSUE TITLE
可能由于我的环境问题（Pycharm python3.8),出现了一个导致死循环的小错误，已自行修正

### ISSUE THREAD

**Issue by Cubakki** [eggplants/get-pixivpy-token#3]
在selenium的81行，
"if self.headless:"会被解释器认为False，从而跳过 try_login，进入之后等待重定向的无限循环

改为"if True:"即解决问题

**Comment by eggplants** [comment]
请给我们提供运行时的代码。

**Comment by Cubakki** [comment]
No exception had been raised, it just performed as "After the input of user and password finished in chorme , the program tended to do nothing but remained static".
Here's the screenshot of the code block.

![Snipaste_2021-09-15_17-19-06](https://user-images.githubusercontent.com/67269648/133407353-c0a04327-a5a9-48ad-9e58-651bc1dda217.png)

**Comment by eggplants** [comment]
@Cubakki try `pip install -U gppt==1.5`, `gppt l` and `gppt lh -u *** -p ***`
