### ISSUE TITLE
Update for PixivPy 3.7.2

### ISSUE THREAD

**Issue by teppyboy** [eggplants/get-pixivpy-token#35]
Currently the latest release target PixivPy 3.7.1 so I can't update pixivpy to 3.7.2 in poetry. You should update it to target pixivpy 3.7.2 or consider changing it to "3.7.*" :eyes:

**Comment by eggplants** [comment]
please try: `pip install git+https://github.com/eggplants/get-pixivpy-token@d2a2b57a085b2a61e6ac0c52835a405b9ef166de`
