### ISSUE TITLE
Update on PyPI

### ISSUE THREAD

**Issue by teppyboy** [eggplants/get-pixivpy-token#41]
The commit d2a2b57a085b2a61e6ac0c52835a405b9ef166de fixes #35, but the PyPI package is still at 2.2.0 and that isn't updated with d2a2b57a085b2a61e6ac0c52835a405b9ef166de, can you update the package on PyPI too?

Using `pip install git+https://github.com/eggplants/get-pixivpy-token@d2a2b57a085b2a61e6ac0c52835a405b9ef166de` does work but in some cases like using Poetry in repl.it (`poetry add git+https://github.com/eggplants/get-pixivpy-token@d2a2b57a085b2a61e6ac0c52835a405b9ef166de`) crashes, and personally i'd prefer an updated release in PyPI since this does fix a minor bug.

**Comment by eggplants** [comment]
Sorry for the delay in my response. I have just published v2.2.1.
