### ISSUE TITLE
Unsupported for python3.7 due to the usage of TypedDict

### ISSUE THREAD

**Issue by narugo1992** [eggplants/get-pixivpy-token#46]
As I tested, this code can not be run on python3.7 because of the usage of `TypedDict`.

You can see the official documentation here: https://docs.python.org/3/library/typing.html#typing.TypedDict

**The `TypedDict` is newly added in python3.8.**

So, is there any plan to support python3.7? If not, you should change >=3.7 in setup.cfg to >=3.8

**Comment by eggplants** [comment]
Released: [v3.1.0](https://pypi.org/project/gppt/3.1.0)
